<a href="https://colab.research.google.com/github/adityasodani03/advancepython/blob/main/pynew2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,1,1,1,4,5])
a

array([1, 2, 3, 1, 1, 1, 4, 5])

In [4]:
np.unique(a, return_index=True, return_counts=True)       #unique function

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 6, 7]), array([4, 1, 1, 1, 1]))

In [6]:
a=np.linspace(1,2,5)         #linspace function
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
## hstack and vstack
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])

In [8]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**PANDAS**

In [10]:
import pandas as pd

(a). Series

In [12]:
a=pd.Series([12,24,43,21])
a

0    12
1    24
2    43
3    21
dtype: int64

In [14]:
type(a)

pandas.core.series.Series

(b). DataFrame

In [15]:
df={
    "emp_id" : [1,2,3,4,5],
    "name" : ['ankit','raj','sam','nishi','vinod'],
    "department" : ['IT','SALES','IT','SALES','IT'],
    "salary" : [20000,23000,90000,32000,80000]
}

In [22]:
df=pd.DataFrame(df)
df

emp_id   name department  salary
0       1  ankit         IT   20000
1       2    raj      SALES   23000
2       3    sam         IT   90000
3       4  nishi      SALES   32000
4       5  vinod         IT   80000

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df.to_csv("/content/emp_data.csv")