<a href="https://colab.research.google.com/github/adityasodani03/advancepython/blob/main/pynew1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4]
type(a)

list

In [5]:
b=np.array(a)
type(b)
b

array([1, 2, 3, 4])

In [7]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print("total no. of rows and columns :",b.shape)   ## shape = n(rows),n(column)
print("total elements :",b.size)   ##size = n(rows)*n(columns)
print("dimension :",b.ndim)   ##  ndim stands for n_dimensions here 2=(x,y)

total no. of rows and columns : (3, 3)
total elements : 9
dimension : 2


**user defined array**

In [13]:
a=[]
size = int(input("enter size :"))
for i in range(size):
  val=int(input("enter number :"))
  a.append(val)
b=np.array(a)
b

enter size :3
enter number :1
enter number :2
enter number :3


array([1, 2, 3])

In [24]:
a=[1,2,"aaaaaaaaaaahhhhhhhaaaaa"]
b=np.array(a)
b

array(['1', '2', 'aaaaaaaaaaahhhhhhhaaaaa'], dtype='<U23')

**Functions in numpy**

In [16]:
a=np.zeros(3)
a


array([0., 0., 0.])

In [17]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
a=np.array([23,45,221,11])
a

array([ 23,  45, 221,  11])

In [26]:
b=np.diag(a)
b

array([[ 23,   0,   0,   0],
       [  0,  45,   0,   0],
       [  0,   0, 221,   0],
       [  0,   0,   0,  11]])

#random module

In [31]:
a=np.random.randint(1,10,4)
a

array([9, 3, 5, 4])

In [33]:
a=np.random.rand(4)
a

array([0.79124395, 0.63854636, 0.87087157, 0.72756857])

In [36]:
np.random.seed(43)
a=np.random.randint(1,10,5)
a

array([5, 1, 2, 6, 1])

**Reshaping the array**
n(rows)*n(column)=total elements

In [37]:
a=np.random.randint(1,50,12)
a

array([18, 28,  3, 47, 31, 24,  1, 36, 12, 26,  2, 48])

In [ ]:
#12 elements
#1*12,12*1
#2*6,6*2
#3*4,4*3

In [38]:
a.reshape(2,6)

array([[18, 28,  3, 47, 31, 24],
       [ 1, 36, 12, 26,  2, 48]])

In [39]:
a.reshape(3,4)

array([[18, 28,  3, 47],
       [31, 24,  1, 36],
       [12, 26,  2, 48]])

**Operations on array**

In [56]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [43]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [44]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [57]:
a=a.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [60]:
x=np.sum(a)    ##total sum
x

np.int64(120)

In [49]:
np.sum(a,axis=0)  ##column wise sum

array([35, 40, 45])

In [50]:
np.sum(a,axis=1)  ##row wise sum

array([ 6, 15, 24, 33, 42])

In [64]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [65]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [66]:
a+b

array([[ 6,  8],
       [10, 12]])

In [67]:
a-b

array([[-4, -4],
       [-4, -4]])

In [68]:
a*b    #this is not the matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [69]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [70]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [71]:
a**2

array([ 1,  4,  9, 16])

In [72]:
a**3

array([ 1,  8, 27, 64])

In [73]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [74]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])